import '@/styles/globals.css';
import type { Metadata } from 'next';

// fonts
import { chong, dante, satoshi } from '@/public/fonts';
import { Overlay } from '@/components/Overlay';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dante.variable} ${satoshi.variable} ${chong.variable} font-satoshi relative antialiased`}
      >
        <Overlay />
        {children}
      </body>
    </html>
  );
}
