import '@/styles/globals.css';
import type { Metadata } from 'next';

// fonts
import { dante, satoshi } from '@/public/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${dante.variable} ${satoshi.variable} font-satoshi antialiased`}>
        {children}
      </body>
    </html>
  );
}
